### ISSUE TITLE
Improve email templates

### ISSUE THREAD

**Issue by underscope** [ExtensionEngine/tailor#517]
## I'm submitting a...

- [ ] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [x] Feature request
- [ ] Documentation issue or request

## Context
- Add logo
- Improve discussion template with context (show last N messages)
- Tweak overall UI

**Comment by hrvojevu** [comment]
@underscope here are some suggestions on improved UI. These include changes on the button (width is now `auto`, color is slightly darker to match logo), divider border style changed to `dashed` (because tailoring). To achieve consistency with logo's across the platform (round logo) new svg file was created since, afaik, it is not possible to have completely rounded container (`border-radius: 50%`) in `mjml`. Suggestions are welcome! 

As far as:
> Improve discussion template with context (show last N messages)

Can you elaborate on that? How many messages do we want to show?


#### Example 1

![Screen Shot 2020-08-21 at 1 12 47 PM](https://user-images.githubusercontent.com/7149531/90884472-1c7e2600-e3b0-11ea-8dc5-80e81d2a2728.png)

#### Example 2

![Screen Shot 2020-08-21 at 1 12 35 PM](https://user-images.githubusercontent.com/7149531/90884480-1ee08000-e3b0-11ea-8267-582d4c8b0ee5.png)

#### Example 3

![Screen Shot 2020-08-21 at 1 13 09 PM](https://user-images.githubusercontent.com/7149531/90884493-22740700-e3b0-11ea-8fbd-868c2078be77.png)

#### Example 4

![Screen Shot 2020-08-21 at 1 10 17 PM](https://user-images.githubusercontent.com/7149531/90884284-c0b39d00-e3af-11ea-9b12-2cd0e91bc481.png)

**Comment by underscope** [comment]
👌 Options 1 and 2 look good to me. Consider just using scissors for the logo (omit circle/background) in primary color and using secondary to accent some details (i.e. name; might be a bit much?)

**Comment by hrvojevu** [comment]
@underscope since accent color (`#37474f`) doesn't really differ from default text color, I would leave it as is. In the image below you can see default (current) text color for name on left side and accent color (`#37474f`) on the right. 

![comparison](https://user-images.githubusercontent.com/7149531/91036821-4893e400-e608-11ea-9e2a-5feb79834c74.png)

**Comment by hrvojevu** [comment]
@underscope regarding 

> Improve discussion template with context (show last N messages)

how many discussion messages do we want to display?

**Comment by underscope** [comment]
@hrvojevu 
Hey,

I made a mistake with color name, I was thinking of secondary (pink) which is used throughout the platform. Up to three makes sense? 

P.S.
Your version with the logo background looks much better ;)

**Comment by hrvojevu** [comment]
@underscope here are suggestions for discussion email template UI update

#### Example 1
![Screen Shot 2020-08-26 at 4 17 42 PM](https://user-images.githubusercontent.com/7149531/91315828-6c962780-e7b8-11ea-95d1-70a543c93278.png)

#### Example 2
![Screen Shot 2020-08-26 at 4 22 20 PM](https://user-images.githubusercontent.com/7149531/91315837-6ef88180-e7b8-11ea-87c3-ce58c1e5cecf.png)

**Comment by mandryllo** [comment]
@hrvojevu Are you sure we need to expose a complete URL to content for the user to copy and paste manually? As far as I remember we exposed it only on reset password email because token was too long and some mail clients would cut them off. That shouldn't happen in this case 🤔
@vladimyr What do you think?

**Comment by hrvojevu** [comment]
@mandryllo not sure really, I thought this was standard practice because welcome mail has URL for user to copy/paste as well.

**Comment by vladimyr** [comment]
I don't have a strong opinion about this one so I tend to follow what others do. Quickly skimming through my inbox resulted in a few Vercel (former Zeit) emails containing copyable URLs. However, that was the case only when email was sent as part of login flow, regular notifications do not have it. Github's and Synk's summary emails also don't contain copyable URLs so it is probably best to stick with the following rule:

**Add URL only if the email is part of the authentication flow, it should be omitted from the regular conversation stuff.**

What do you think?
