### ISSUE TITLE
PDF component displays errors for some PDF URLs

### ISSUE THREAD

**Issue by kjuej** [ExtensionEngine/tailor#543]
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Context
URL used: https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf

<img width="1292" alt="Screen Shot 2020-06-08 at 11 33 34" src="https://user-images.githubusercontent.com/34127147/84015325-f5e94b00-a97b-11ea-834f-39997d2f0171.png">

**Comment by vladimyr** [comment]
Unfortunately, this is unfixable. adobe.com explicitly prohibits embedding this particular resource using CSP:
```
~
➜ https --print h https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: max-age=9777
Connection: keep-alive
Content-Length: 88226
Content-Security-Policy: frame-ancestors *.adobe.com  http://adobe.lookbookhq.com https://adobe.lookbookhq.com http://adobeenterprise.lookbookhq.com https://adobeenterprise.lookbookhq.com
Content-Type: application/pdf
Date: Tue, 09 Jun 2020 19:30:06 GMT
Expires: Tue, 09 Jun 2020 22:13:03 GMT
Last-Modified: Wed, 05 Jan 2005 19:56:38 GMT
Server: Apache
Server-Timing: cdn-cache; desc=HIT
Server-Timing: edge; dur=1
Strict-Transport-Security: max-age=86400
X-Adobe-Loc: ew1
X-Adobe-Source: 128.74
X-Content-Type-Options: nosniff
```

Check console output on this little [demo](https://gistcdn.rawgit.org/vladimyr/39e210e19aa2cad4c00f1f93b200e54b/4a99330eb8e46baf7cb9c03388f23a55c5435b91/index.html). You should see something similar inside Tailor's console output.

There might be a way to detect this in javascript (needs investigation) and hopefully, present more helpful error message to the end-user but that is really an improvement rather than bugfix.
