### ISSUE TITLE
Improve validation for exam time limit

### ISSUE THREAD

**Issue by kjuej** [ExtensionEngine/tailor#592]
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Context
Exam time limit can have multiple "-","+","e" characters.
<img width="339" alt="Screen Shot 2020-09-01 at 10 52 30" src="https://user-images.githubusercontent.com/34127147/91829162-603f1e00-ec41-11ea-8330-67652322c908.png">

**Comment by hrvojevu** [comment]
This issue occurs due to `e`, `-` and `+` are being interpreted as numbers when used in `number` type input. Vee-validate doesn't handle this particular use case, more info here: https://github.com/logaretm/vee-validate/issues/1667.

Solution to this problem is either disallowing `e`, `+`, `-` keys via `@keypress` event or removing `type=number` attribute on input thus allowing all characters and allowing vee-validate to validate.
