### ISSUE TITLE
Add validation message for invalid embed url

### ISSUE THREAD

**Issue by kjuej** [ExtensionEngine/tailor#594]
## I'm submitting a...

- [x] Bug report  
- [ ] Regression (a behavior that used to work and stopped working in a new release)
- [ ] Feature request
- [ ] Documentation issue or request

## Context
No validation message displayed for invalid embed url:
<img width="1127" alt="Screen Shot 2020-09-01 at 10 58 32" src="https://user-images.githubusercontent.com/34127147/91829774-2de1f080-ec42-11ea-99fc-7be8116825e7.png">

**Comment by hrvojevu** [comment]
@kjuej this is due to `hide-details` prop on `v-text-field` in the `tce-embed` toolbar component. I figure this was set due to toolbar height being too low to display error messages. @underscope in order to display error messages correctly toolbar height needs to increase. Additionally, it would makes sense to me that we increase across all toolbars for consistency sake.
